version: '2.1'

services:
  genial:
    image: $DOCKER_UNTESTED_IMAGE_PATH
    environment:
      SPRING_APPLICATION_JSON: >
        {
        }
      DEBUG_PORT: 8787
    ports:
      - "8080:8080"
      - "8787:8787"

  # $ docker exec -it genial_my-sql_1 bash
  # $ mysql -u root -p
  my-sql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "genial_db"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d